# Opacity

active-opacity = 0.90;
inactive-opacity = 0.90;
# inactive-opacity-override = true;
inactive-dim = 0.1;
menu-opacity = 0.8;
frame-opacity = 1;

opacity-rule = [
    	"99:class_g = 'Polybar'",
    	"90:class_g = 'vscodium'",
    	"90:class_g = 'discord'",
    	"90:class_g = 'Zathura'",
    	"80:class_g = 'Deluge'",
    	"80:class_g = 'Lxappearance'",
    	"95:class_g = 'Steam'",
    	"80:class_g = 'Pcmanfm'",
    	"99:class_g = 'firefox'",
    	"99:class_g = 'vlc'",
        "99:class_g = 'mpv'",
    	"99:class_g = 'Minecraft 1.12.2'",
	    "90:class_g = 'kitty'",
        "90:class_g = 'emacs'",
	    "99:class_g = 'vis'",
        "99:class_g = 'KSP.x86_64'",
        "99:class_g = 'Civ6Sub'",
        "99:class_g = 'qemu'",
        "99:class_g = 'factorio'",
        "99:class_g = 'osu!.exe'",
        "99:class_g = 'sailaway.exe'",
        "99:class_g = 'among us.exe'",
        "99:class_g = 'Civ5XP'",
        "99:class_g = 'darktable'",
        "99:class_g = 'StardewValley.bin.x86_64'",
        "99:class_g = 'abzugame-win64-shipping.exe'",
        "99:class_g = 'Enigmatica 2'",
];

# Dimming

#inactive-dim = 0.5;		        # Dim inactive windows. (0.0 - 1.0, defaults to 0).
inactive-dim-exclude = [ 
    "class_g = 'Rofi'",
    "class_g = 'mpv'",
    "class_g = 'Polybar'",
    "class_g = 'firefox'",
    "class_g = 'vlc'"
];

# Fading

fading = true;			        # Fade windows during opacity changes.
fade-delta = 5;		        # The time between steps in a fade in milliseconds. (default 10).
fade-in-step = 0.03;		    # Opacity change between steps while fading in. (default 0.028).
fade-out-step = 0.03;		    # Opacity change between steps while fading out. (default 0.03).

# Blur

blur-background = true;
blur-background-frame = false;
blur-background-fixed = false;
blur-kern = "3x3box";
blur-method = "kawase";
blur-strength = 10;

blur-background-exclude = [
	"class_g = 'Screenkey'",
	"class_g = 'Polybar'"
];

# Other

mark-wmwin-focused = true;   	# Try to detect WM windows and mark them as active.
mark-ovredir-focused = true; 
detect-rounded-corners = true;
detect-client-opacity = true;
glx-no-stencil = true;
paint-on-overlay = true;
unredir-if-possible = true;
glx-copy-from-front = false;
glx-swap-method = "undefined";

refresh-rate = 0;
vsync = "opengl-swc";
EnablePageFlip = true;
backend = "glx";
